### ISSUE TITLE
Username and password - Reg

### ISSUE THREAD

**Issue by ABHISHEK1967** [alexmingoia/express-elasticsearch-logger#7]
Hi @team,

How to have username and password protected host in the config as I don't find a provision for that in the config options ?
We have hosted elastic client in a remote server and would like to send the logs of corresponding microservice

**Comment by alexmingoia** [comment]
The configuration object is passed to the elasticsearch client. It accepts whatever options [elasticsearch](https://github.com/elastic/elasticsearch-js) module does.
